/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gusta
 */
import javax.swing.*;
import java.awt.*;
import com.sun.j3d.utils.universe.SimpleUniverse;
import com.sun.j3d.utils.geometry.Box;
import javax.media.j3d.*;
import javax.vecmath.*;

public class MainScene extends JFrame {

    public static TransformGroup movableBoxTG;
    public static BoundingBox staticBoxBounds;

    public MainScene() {
        setTitle("Colisión en Java 3D");
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        // Crear el canvas y la configuración gráfica
        GraphicsConfiguration config = SimpleUniverse.getPreferredConfiguration();
        Canvas3D canvas3D = new Canvas3D(config);
        add("Center", canvas3D);

        // Crear el universo y la escena
        SimpleUniverse universe = new SimpleUniverse(canvas3D);
        BranchGroup scene = createSceneGraph();
        scene.compile();  // Compilar la escena para optimización
        universe.getViewingPlatform().setNominalViewingTransform();
        universe.addBranchGraph(scene);  // Asignar la escena al universo

        // Asegurarse de que el JFrame sea visible y correcto
        setVisible(true);
    }

    private BranchGroup createSceneGraph() {
        BranchGroup scene = new BranchGroup();

        // Caja movible
        Box movableBox = new Box(0.1f, 0.1f, 0.1f, null);
        movableBoxTG = new TransformGroup();
        movableBoxTG.setCapability(TransformGroup.ALLOW_TRANSFORM_WRITE);
        movableBoxTG.setCapability(TransformGroup.ALLOW_TRANSFORM_READ);
        Transform3D initialTransform = new Transform3D();
        initialTransform.setTranslation(new Vector3f(0.0f, 0.0f, 0.0f));
        movableBoxTG.setTransform(initialTransform);
        movableBoxTG.addChild(movableBox);
        scene.addChild(movableBoxTG);

        // Caja estática
        Box staticBox = new Box(0.1f, 0.1f, 0.1f, null);
        Transform3D staticTransform = new Transform3D();
        staticTransform.setTranslation(new Vector3f(0.4f, 0.0f, 0.0f));
        TransformGroup staticBoxTG = new TransformGroup(staticTransform);
        staticBoxTG.addChild(staticBox);
        scene.addChild(staticBoxTG);

        // Definir límites de colisión
        staticBoxBounds = new BoundingBox(
                new Point3d(0.3, -0.1, -0.1), new Point3d(0.5, 0.1, 0.1));

        // Comportamiento de teclas
        KeyBehavior keyBehavior = new KeyBehavior(this);
        keyBehavior.setSchedulingBounds(new BoundingSphere(new Point3d(0, 0, 0), 100));
        scene.addChild(keyBehavior);

        return scene;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScene().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
